name: Build Backend Docker Image

on:
  push:
    branches: [ main ]  # You can adjust this trigger for other branches

jobs:
  build:
    runs-on: ubuntu-latest  # Replace with desired build environment

    steps:
      - uses: actions/checkout@v3  # Checkout code from repository
      - name: Use Node.js 16 (replace with your backend language)
        uses: actions/setup-node@v3
        with:
          node-version: 16.x  # Adjust Node.js version if needed (or replace with Python, Java, etc.)
      - name: Install dependencies
        working-directory: /home/runner/work/prompt-manager/prompt-manager/prompt-manager-server
        run: npm install  # Replace with your backend dependency manager (e.g., pip for Python)
      - name: Login to Docker Hub (optional)
        uses: docker/login-action@v2  # Replace with your registry login action
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        working-directory: /home/runner/work/prompt-manager/prompt-manager/prompt-manager-server
        run: docker build -t mohamadaskari/backend-image:latest . && docker push mohamadaskari/backend-image:latest