name: Build Frontend Docker Image

on:
  push:
    branches: [ main ]  # You can adjust this trigger for other branches

jobs:
  build:
    runs-on: ubuntu-latest  # Replace with desired build environment
 
    steps:
      - uses: actions/checkout@v3  # Checkout code from repository
      - name: Use Node.js 16  # Adjust Node.js version as needed
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        working-directory: /home/runner/work/prompt-manager/prompt-manager/prompt-manager-ui
        run: npm install  # Replace with your frontend dependency manager
      - name: Build frontend
        working-directory: /home/runner/work/prompt-manager/prompt-manager/prompt-manager-ui
        run: npm run build  # Replace with your build command
      - name: Login to Docker Hub (optional)
        uses: docker/login-action@v2  # Replace with your registry login action
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: docker build -t mohamadaskari/frontend-image:latest . && docker push mohamadaskari/frontend-image:latest