# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [14.x, 16.x, 18.x]
    #     redis-version: [6, 7]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    - name: Start Redis
      uses: supercharge/redis-github-action@1.7.0
      with:
          redis-version: 6
        # redis-version: ${{ matrix.redis-version }}
        
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      
      with:
        node-version: 16.x
        # node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - working-directory: /home/runner/work/prompt-manager/prompt-manager/prompt-manager-server
      run: npm ci
    - working-directory: /home/runner/work/prompt-manager/prompt-manager/prompt-manager-server
      run: npm run build --if-present
    - name: Run tests
      working-directory: /home/runner/work/prompt-manager/prompt-manager/prompt-manager-server
      run: npm test
